INGREDIENT_VOCAB = [
    "onion", "garlic", "ginger", "tomato", "potato", "carrot", "bell pepper",
    "spinach", "kale", "broccoli", "cauliflower", "zucchini", "eggplant",
    "cucumber", "lettuce", "avocado", "green beans", "peas", "corn",
    "mushrooms", "cabbage", "radish", "pumpkin", "bitter gourd", "sweet potato",
    "yam", "squash", "chard", "celery", "leeks", "shallots", "fennel",
    "beetroot", "beets", "chickpeas", "mint", "oats", "channa",
    "salt", "pepper", "olive oil", "coconut oil", "ghee", "butter",
    "honey", "sugar", "brown sugar", "maple syrup", "vinegar", "soy sauce",
    "mustard", "ketchup", "hot sauce", "tahini", "chia seeds", "flaxseeds",
    "sesame seeds", "nuts", "coconut", "quinoa", "couscous", "rice", "pasta",
    "lentils", "beans", "tofu", "tempeh", "fish sauce", "coconut milk",
    "chicken broth", "vegetable broth", "eggs", "cheese", "cream", "yogurt",
    "milk", "buttermilk", "heavy cream", "chicken", "beef", "lamb", "pork",
    "salmon", "tuna", "shrimp", "fish",
    "flour", "cornstarch", "cocoa powder", "chocolate chips", "vanilla extract",
    "cinnamon", "nutmeg", "cardamom", "cloves", "curry powder", "paprika",
    "chili powder", "cumin", "coriander", "saffron", "bay leaves",
    "granola", "pesto", "marinara sauce", "salsa",
    "baking powder", "baking soda", "wheat flour",
]