# Generated by Django 5.1.14 on 2026-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SafetyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("allergen_contains", "Allergen Contains"),
                            ("nutrient_threshold", "Nutrient Threshold"),
                            ("diet_violation", "Diet Violation"),
                            ("ingredient_conflict", "Ingredient Conflict"),
                        ],
                        default="allergen_contains",
                        max_length=30,
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        default=dict,
                        help_text='Rule condition definition. Examples:\n  Allergen: {"allergen": "peanuts"}\n  Nutrient: {"nutrient": "carbs", "max_value": 60, "health_condition": "diabetic"}\n  Diet: {"diet": "vegan", "check": "is_vegetarian"}\n  Ingredient: {"ingredient": "shellfish", "health_condition": "shellfish allergy"}',
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Warning message template. Use {recipe_name}, {allergen}, {nutrient}, {value}, {threshold}, etc."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["severity", "key"],
            },
        ),
    ]
