# Generated by Django 5.1.14 on 2026-04-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("omnivore", "Omnivore"),
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("pescatarian", "Pescatarian"),
                            ("other", "Other"),
                        ],
                        default="omnivore",
                        max_length=20,
                    ),
                ),
                ("health_conditions", models.JSONField(blank=True, default=list)),
                ("allergies", models.JSONField(blank=True, default=list)),
                ("disliked_ingredients", models.JSONField(blank=True, default=list)),
                ("preferred_cuisines", models.JSONField(blank=True, default=list)),
                ("calorie_target", models.IntegerField(blank=True, null=True)),
                ("protein_target_g", models.FloatField(blank=True, null=True)),
                ("carbs_target_g", models.FloatField(blank=True, null=True)),
                ("fat_target_g", models.FloatField(blank=True, null=True)),
                ("max_cooking_time_min", models.IntegerField(blank=True, null=True)),
                ("spice_tolerance", models.IntegerField(blank=True, null=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
