# Generated by Django 5.1.14 on 2026-04-24 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("recipes", "0014_recipe_is_vegetarian"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRecipeInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("saved", "Saved"),
                            ("liked", "Liked"),
                            ("disliked", "Disliked"),
                            ("cooked", "Cooked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "interaction_type"],
                        name="accounts_us_user_id_643efc_idx",
                    ),
                    models.Index(
                        fields=["recipe", "interaction_type"],
                        name="accounts_us_recipe__372cc0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "recipe", "interaction_type"),
                        name="unique_user_recipe_interaction_type",
                    )
                ],
            },
        ),
    ]
