# Generated by Django 5.1.14 on 2026-04-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userrecipeinteraction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRecipeInteraction",
        ),
    ]
