# Generated by Django 5.1.2 on 2024-10-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("cooking_time", models.IntegerField()),
                ("image", models.URLField(blank=True, null=True)),
                ("meal_type", models.CharField(blank=True, max_length=100, null=True)),
                ("health_benefits", models.TextField(blank=True, null=True)),
                ("diet_restrictions", models.TextField(blank=True, null=True)),
                (
                    "flavour_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cuisine", models.CharField(blank=True, max_length=100, null=True)),
                ("nutritional_info", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
