# Generated by Django 5.1.2 on 2024-10-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="nutritional_info",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
