# Generated by Django 5.1.2 on 2024-10-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(),
        ),
    ]
