# Generated by Django 5.1.2 on 2024-10-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_prep_time_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="spice_level",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
