# Generated by Django 5.1.2 on 2024-11-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipe_servings_recipe_spice_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
