# Generated by Django 5.1.2 on 2024-11-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cooking_time",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cuisine",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="diet_restrictions",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="flavour_type",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="health_benefits",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="meal_type",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="name",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="nutritional_info",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="prep_time",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="servings",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="spice_level",
        ),
    ]
