# Generated by Django 5.1.2 on 2024-11-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_remove_recipe_cooking_time_remove_recipe_cuisine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cuisine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="diet_restrictions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="flavour_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="health_benefits",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredient_list",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="nutritional_info",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="spice_level",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
