# Generated by Django 5.1.2 on 2024-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_recipe_cooking_time_recipe_cuisine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredient_list",
        ),
        migrations.AddField(
            model_name="recipe",
            name="parse_ingredient",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
