# Generated by Django 5.1.2 on 2024-11-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_remove_recipe_ingredient_list_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="recipe",
        ),
    ]
