# Generated by Django 5.1.2 on 2024-11-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0011_delete_recipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("protein", models.FloatField()),
                ("carbs", models.FloatField()),
                ("fat", models.FloatField()),
                ("fiber", models.FloatField()),
                ("vitamins", models.JSONField()),
                ("calories", models.IntegerField()),
                ("cooking_time", models.IntegerField()),
                ("spicy_level", models.IntegerField()),
            ],
        ),
    ]
