# Generated by Django 5.1.2 on 2024-11-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
