# Generated by Django 5.1.2 on 2024-11-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_recipe_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_vegetarian",
            field=models.BooleanField(default=False),
        ),
    ]
