# Generated by Django 5.1.14 on 2026-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_recipe_is_vegetarian"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="allergens",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="serving_size_g",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="sodium_mg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="sugar_g",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
