# Generated by Django 5.1.14 on 2026-04-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_recipe_allergens_recipe_is_gluten_free_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="allergens",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_gluten_free",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_vegan",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="serving_size_g",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="sodium_mg",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="sugar_g",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
    ]
