# Generated by Django 5.1.14 on 2026-04-24 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0015_recipe_allergens_recipe_is_gluten_free_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("workout", "Workout"),
                            ("low_carb", "Low-Carb"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("num_meals", models.IntegerField(default=4)),
                ("target_calories", models.IntegerField(blank=True, null=True)),
                ("total_calories", models.IntegerField(default=0)),
                ("total_protein_g", models.FloatField(default=0)),
                ("total_carbs_g", models.FloatField(default=0)),
                ("total_fat_g", models.FloatField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="MealPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("servings", models.FloatField(default=1.0)),
                ("calories", models.IntegerField(default=0)),
                ("protein_g", models.FloatField(default=0)),
                ("carbs_g", models.FloatField(default=0)),
                ("fat_g", models.FloatField(default=0)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="planner.mealplan",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan_items",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["meal_type"],
            },
        ),
    ]
