# Generated by Django 5.1.14 on 2026-04-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplanitem",
            name="meal_plan",
        ),
        migrations.RemoveField(
            model_name="mealplanitem",
            name="recipe",
        ),
        migrations.DeleteModel(
            name="MealPlan",
        ),
        migrations.DeleteModel(
            name="MealPlanItem",
        ),
    ]
