# Generated by Django 5.1.14 on 2026-04-24 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_query", models.TextField()),
                ("normalized_query", models.TextField()),
                ("parsed_filters", models.JSONField(blank=True, default=dict)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api_v1", "API v1"),
                            ("legacy_chatbot", "Legacy Chatbot"),
                        ],
                        default="api_v1",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "created_at"],
                        name="recommendat_source_64b390_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="recommendat_user_id_ed1550_idx",
                    ),
                ],
            },
        ),
    ]
