# Generated by Django 5.1.14 on 2026-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="searchlog",
            name="recommendat_source_64b390_idx",
        ),
        migrations.RemoveIndex(
            model_name="searchlog",
            name="recommendat_user_id_ed1550_idx",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="source",
        ),
        migrations.AlterField(
            model_name="searchlog",
            name="latency_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="searchlog",
            name="result_count",
            field=models.IntegerField(default=0),
        ),
    ]
